steps:
- id: 'tag'
  name: 'bridgecrew/yor'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
 
        yor tag -d . --config-file tag-custom.yaml 
    
        yor tag -d . --output cli --output-json-file hasil.json

        git config user.name "saktil"

        git config user.email "leosaragih001@gmail.com"

        git init

        git add .

        git commit -m "update from ci"

        git remote add origin https://github.com/saktil/test-yor-ci.git

        git branch -M master

        git push -u origin master
        
      
     
      
